version: '3.8'
services:
  gogis:
    build: ./
    command: ./gogis
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_PASSWORD=postgres
  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./.database/gostgres/data:/var/lib/postgresql/data
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    restart: always

volumes:
  postgres_data:

  pgadmin_data:
 

